#include "CURSOS_EN.hpp"

const EstruturaCursos &CURSOS_EN() {
    static const EstruturaCursos cursos = {CursoCurricular{
        QString::fromUtf8(u8"Civil Engineering"),
        QList<EmentaCurricular>{
            EmentaCurricular{
                QString::fromUtf8(u8"Syllabus - 2011"),
                QList<SemestreCurricular>{
                    SemestreCurricular{QString::fromUtf8(u8"1st Semester"),
                                       QStringList{QString::fromUtf8(u8"Differential and Integral Calculus I – CM201"),
                                                   QString::fromUtf8(u8"Applied Electricity – TE144"),
                                                   QString::fromUtf8(u8"Graphic Expression I – CD027"),
                                                   QString::fromUtf8(u8"Analytical Geometry – CM045"),
                                                   QString::fromUtf8(u8"Introduction to Engineering – TC022"),
                                                   QString::fromUtf8(u8"General Mechanics I – TC021"),
                                                   QString::fromUtf8(u8"Computer Programming – CI208")}},
                    SemestreCurricular{QString::fromUtf8(u8"2nd Semester"),
                                       QStringList{QString::fromUtf8(u8"Linear Algebra – CM005"),
                                                   QString::fromUtf8(u8"Differential and Integral Calculus II – CM202"),
                                                   QString::fromUtf8(u8"Civil Construction I – TC024"),
                                                   QString::fromUtf8(u8"Graphic Expression II – CD028"),
                                                   QString::fromUtf8(u8"General Mechanics II – TC023"),
                                                   QString::fromUtf8(u8"Numerical Methods – CI202")}},
                    SemestreCurricular{QString::fromUtf8(u8"3rd Semester"),
                                       QStringList{QString::fromUtf8(u8"Calculus III – CM043"),
                                                   QString::fromUtf8(u8"Civil Construction II – TC025"),
                                                   QString::fromUtf8(u8"Statistics II – CE003"),
                                                   QString::fromUtf8(u8"Fluid Mechanics I – TH019"),
                                                   QString::fromUtf8(u8"General Mechanics III – TC027"),
                                                   QString::fromUtf8(u8"Strength of Materials I – TC026"),
                                                   QString::fromUtf8(u8"Topography I – GA069")}},
                    SemestreCurricular{
                        QString::fromUtf8(u8"4th Semester"),
                        QStringList{QString::fromUtf8(u8"Introduction to Geotechnical Engineering – TC029"),
                                    QString::fromUtf8(u8"Environmental Science – TH022"),
                                    QString::fromUtf8(u8"Construction Materials I – TC030"),
                                    QString::fromUtf8(u8"Fluid Mechanics II – TH021"),
                                    QString::fromUtf8(u8"Strength of Materials II – TC028"),
                                    QString::fromUtf8(u8"Transportation Systems – TT046"),
                                    QString::fromUtf8(u8"Topography II – GA070")}},
                    SemestreCurricular{QString::fromUtf8(u8"5th Semester"),
                                       QStringList{QString::fromUtf8(u8"Sanitary Infrastructure of Cities – TH025"),
                                                   QString::fromUtf8(u8"Hydraulics – TH020"),
                                                   QString::fromUtf8(u8"Roadway Infrastructure – TT048"),
                                                   QString::fromUtf8(u8"Soil Mechanics Laboratory – TC033"),
                                                   QString::fromUtf8(u8"Construction Materials II – TC031"),
                                                   QString::fromUtf8(u8"Structural Mechanics I – TC032")}},
                    SemestreCurricular{
                        QString::fromUtf8(u8"6th Semester"),
                        QStringList{QString::fromUtf8(u8"Formative Activities – AAC005"),
                                    QString::fromUtf8(u8"Construction and Conservation Equipment – TT047"),
                                    QString::fromUtf8(u8"Experimental Hydraulics and Hydrology – TH027"),
                                    QString::fromUtf8(u8"Hydrology – TH024"),
                                    QString::fromUtf8(u8"Construction Materials III – TC034"),
                                    QString::fromUtf8(u8"Structural Mechanics II – TC036"),
                                    QString::fromUtf8(u8"Soil Mechanics – TC035")}},
                    SemestreCurricular{QString::fromUtf8(u8"7th Semester"),
                                       QStringList{QString::fromUtf8(u8"Civil Construction III – TC038"),
                                                   QString::fromUtf8(u8"Water Resources Engineering – TH026"),
                                                   QString::fromUtf8(u8"Social Engineering – TH045"),
                                                   QString::fromUtf8(u8"Concrete Structures I – TC037"),
                                                   QString::fromUtf8(u8"Construction Materials Laboratory – TC039"),
                                                   QString::fromUtf8(u8"Geotechnical Works – TC066"),
                                                   QString::fromUtf8(u8"Transport Planning – TT049"),
                                                   QString::fromUtf8(u8"Environmental Sanitation I – TH028")}},
                    SemestreCurricular{QString::fromUtf8(u8"8th Semester"),
                                       QStringList{QString::fromUtf8(u8"Civil Construction IV – TC042"),
                                                   QString::fromUtf8(u8"Engineering Economy I – TT007"),
                                                   QString::fromUtf8(u8"Supervised Internship – TC046"),
                                                   QString::fromUtf8(u8"Supervised Internship – TH043"),
                                                   QString::fromUtf8(u8"Supervised Internship – TT054"),
                                                   QString::fromUtf8(u8"Concrete Structures II – TC040"),
                                                   QString::fromUtf8(u8"Foundation Geotechnics – TC041"),
                                                   QString::fromUtf8(u8"Pavement – TT051"),
                                                   QString::fromUtf8(u8"Environmental Sanitation II – TH029")}},
                    SemestreCurricular{
                        QString::fromUtf8(u8"9th Semester"),
                        QStringList{QString::fromUtf8(u8"Engineering Management I – TT008"),
                                    QString::fromUtf8(u8"Building Structures I – TC044"),
                                    QString::fromUtf8(u8"Steel Structures I – TC043"),
                                    QString::fromUtf8(u8"Project Management – TC045"),
                                    QString::fromUtf8(u8"Building Systems, Hydraulic and Sanitary – TH030"),
                                    QString::fromUtf8(u8"Final Course Project I – TC081"),
                                    QString::fromUtf8(u8"Final Course Project I – TH061"),
                                    QString::fromUtf8(u8"Final Course Project I – TT071")}},
                    SemestreCurricular{QString::fromUtf8(u8"10th Semester"),
                                       QStringList{QString::fromUtf8(u8"Final Course Project II – TC082"),
                                                   QString::fromUtf8(u8"Final Course Project II – TH062"),
                                                   QString::fromUtf8(u8"Final Course Project II – TT072")}},
                    SemestreCurricular{
                        QString::fromUtf8(u8"Electives (minimum 6)"),
                        QStringList{
                            QString::fromUtf8(u8"Environmental Impact Assessment – TT059"),
                            QString::fromUtf8(u8"Engineering Valuations – TC064"),
                            QString::fromUtf8(u8"Traffic Engineering – TT056"),
                            QString::fromUtf8(u8"Economic Engineering of Water Resources – TH035"),
                            QString::fromUtf8(u8"Social Engineering – TH045"),
                            QString::fromUtf8(u8"Concrete Structures III – TC054"),
                            QString::fromUtf8(u8"Building Structures II – TC056"),
                            QString::fromUtf8(u8"Wood Structures – TC057"),
                            QString::fromUtf8(u8"Steel Structures II – TC055"),
                            QString::fromUtf8(u8"Graphic Expression III – CD035"),
                            QString::fromUtf8(u8"Railways – TT066"),
                            QString::fromUtf8(u8"Engineering Geology – TC049"),
                            QString::fromUtf8(u8"Environmental Geotechnics – TC053"),
                            QString::fromUtf8(u8"Applied Geotechnics to Transport Routes – TT065"),
                            QString::fromUtf8(u8"Landslide and Retaining Structures Geotechnics – TC052"),
                            QString::fromUtf8(u8"Project Management – TC062"),
                            QString::fromUtf8(u8"Water Resources Management – TH036"),
                            QString::fromUtf8(u8"Highways and Urban Roads Management – TT063"),
                            QString::fromUtf8(u8"Environmental Hydraulics – TH033"),
                            QString::fromUtf8(u8"River Hydraulics – TH032"),
                            QString::fromUtf8(u8"Specialized Building Installations – TC065"),
                            QString::fromUtf8(u8"Introduction to Occupational Safety Engineering – TT068"),
                            QString::fromUtf8(u8"Legislation and Professional Practice – TC061"),
                            QString::fromUtf8(u8"Logistics and Transport – TT058"),
                            QString::fromUtf8(u8"Rock Mechanics – TC051"),
                            QString::fromUtf8(u8"Finite Element Method Applied to Structural Engineering – TC059"),
                            QString::fromUtf8(u8"Urban Transport Planning and Modeling – TT060"),
                            QString::fromUtf8(u8"Planning and Management of Urban Systems – TH042"),
                            QString::fromUtf8(u8"Bridges and Special Structures – TC058"),
                            QString::fromUtf8(u8"Ports and Waterways – TT067"),
                            QString::fromUtf8(u8"Road Works Project – TT064"),
                            QString::fromUtf8(u8"Architecture Projects – TC060"),
                            QString::fromUtf8(u8"Urban Drainage Projects – TH037"),
                            QString::fromUtf8(u8"Hydraulic Works Projects – TH031"),
                            QString::fromUtf8(u8"Road Works Projects – TT064"),
                            QString::fromUtf8(u8"Urban Solid Waste Management Projects – TH038"),
                            QString::fromUtf8(u8"Environmental Sanitation Projects – TH039"),
                            QString::fromUtf8(u8"Sanitary Hydraulic Systems Projects – TH040"),
                            QString::fromUtf8(u8"Environmental Quality and Conservation – TH041"),
                            QString::fromUtf8(u8"Road Safety – TT061"),
                            QString::fromUtf8(u8"Water Resources Systems – TH034"),
                            QString::fromUtf8(u8"Geotechnical Investigation and Instrumentation Techniques – TC050"),
                            QString::fromUtf8(u8"Advanced Pavement Topics – TT062"),
                            QString::fromUtf8(u8"Advanced Geotechnics Topics – TC048"),
                            QString::fromUtf8(u8"Public Transport – TT057")}}}},
            EmentaCurricular{
                QString::fromUtf8(u8"Syllabus - 2023"),
                QList<SemestreCurricular>{
                    SemestreCurricular{
                        QString::fromUtf8(u8"1st Semester"),
                        QStringList{QString::fromUtf8(u8"Graphic Expression A – CEG019"),
                                    QString::fromUtf8(u8"Fundamentals of Computer Programming – CI182"),
                                    QString::fromUtf8(u8"Pre-Calculus – CM310"),
                                    QString::fromUtf8(u8"Physics I – TC501"),
                                    QString::fromUtf8(u8"Applied Chemistry – TC502"),
                                    QString::fromUtf8(u8"Introduction to Engineering and Innovation – TC591"),
                                    QString::fromUtf8(u8"Introduction to Engineering and Innovation – TH591"),
                                    QString::fromUtf8(u8"Introduction to Engineering and Innovation – TT591")}},
                    SemestreCurricular{
                        QString::fromUtf8(u8"2nd Semester"),
                        QStringList{
                            QString::fromUtf8(u8"Numerical Methods – CI202"),
                            QString::fromUtf8(u8"Introduction to Analytical Geometry and Linear Algebra – CM303"),
                            QString::fromUtf8(u8"Calculus 1 – CM311"),
                            QString::fromUtf8(u8"Architectural Drawing – TC503"),
                            QString::fromUtf8(u8"Structural Analysis I – TC504"),
                            QString::fromUtf8(u8"Physics II – TH512")}},
                    SemestreCurricular{QString::fromUtf8(u8"3rd Semester"),
                                       QStringList{QString::fromUtf8(u8"Introduction to Statistics – CE009"),
                                                   QString::fromUtf8(u8"Calculus 2 – CM312"),
                                                   QString::fromUtf8(u8"Topography I – GA175"),
                                                   QString::fromUtf8(u8"Civil Construction I – TC505"),
                                                   QString::fromUtf8(u8"Structural Analysis II – TC506"),
                                                   QString::fromUtf8(u8"Structural Systems – TC507"),
                                                   QString::fromUtf8(u8"Fluid Mechanics I – TH501"),
                                                   QString::fromUtf8(u8"Transportation Systems – TT501")}},
                    SemestreCurricular{
                        QString::fromUtf8(u8"4th Semester"),
                        QStringList{QString::fromUtf8(u8"Calculus 4 – CM314"),
                                    QString::fromUtf8(u8"Topography II – GA176"),
                                    QString::fromUtf8(u8"Civil Construction II – TC508"),
                                    QString::fromUtf8(u8"Solid Mechanics I – TC509"),
                                    QString::fromUtf8(u8"Construction Materials I – TC510"),
                                    QString::fromUtf8(u8"Civil Construction Materials Laboratory – TC511"),
                                    QString::fromUtf8(u8"Fluid Mechanics II – TH502"),
                                    QString::fromUtf8(u8"Experimental Fluid Mechanics – TH503")}},
                    SemestreCurricular{
                        QString::fromUtf8(u8"5th Semester"),
                        QStringList{QString::fromUtf8(u8"Geological Characterization - Geotechnical – TC512"),
                                    QString::fromUtf8(u8"Solid Mechanics II – TC513"),
                                    QString::fromUtf8(u8"Construction Materials II – TC514"),
                                    QString::fromUtf8(u8"Hydraulics – TH504"),
                                    QString::fromUtf8(u8"Environmental Science – TH508"),
                                    QString::fromUtf8(u8"Transport Planning and Operation – TT502"),
                                    QString::fromUtf8(u8"Civil Engineering and Sustainability – TC592"),
                                    QString::fromUtf8(u8"Civil Engineering and Sustainability – TH592"),
                                    QString::fromUtf8(u8"Civil Engineering and Sustainability – TT592")}},
                    SemestreCurricular{QString::fromUtf8(u8"6th Semester"),
                                       QStringList{QString::fromUtf8(u8"Soil Hydraulics – TC515"),
                                                   QString::fromUtf8(u8"Structural Analysis III – TC516"),
                                                   QString::fromUtf8(u8"Civil Construction III – TC517"),
                                                   QString::fromUtf8(u8"Hydrology – TH505"),
                                                   QString::fromUtf8(u8"Experimental Hydraulics and Hydrology – TH506"),
                                                   QString::fromUtf8(u8"Earthmoving and Paving Equipment – TT503"),
                                                   QString::fromUtf8(u8"City Structuring – TH593"),
                                                   QString::fromUtf8(u8"City Structuring – TT593")}},
                    SemestreCurricular{QString::fromUtf8(u8"7th Semester"),
                                       QStringList{QString::fromUtf8(u8"Soils Mechanics – TC518"),
                                                   QString::fromUtf8(u8"Concrete Structures I – TC519"),
                                                   QString::fromUtf8(u8"Project Management – TC520"),
                                                   QString::fromUtf8(u8"Water Resources Engineering – TH507"),
                                                   QString::fromUtf8(u8"Environmental Sanitation I – TH509"),
                                                   QString::fromUtf8(u8"Engineering Economy – TT504"),
                                                   QString::fromUtf8(u8"Urban Engineering – TH594"),
                                                   QString::fromUtf8(u8"Urban Engineering – TT594")}},
                    SemestreCurricular{
                        QString::fromUtf8(u8"8th Semester"),
                        QStringList{QString::fromUtf8(u8"Geotechnical Works – TC521"),
                                    QString::fromUtf8(u8"Concrete Structures II – TC522"),
                                    QString::fromUtf8(u8"Environmental Sanitation II – TH510"),
                                    QString::fromUtf8(u8"Roads – TT505"), QString::fromUtf8(u8"Pavement – TT506"),
                                    QString::fromUtf8(u8"Transportation Laboratory – TT507"),
                                    QString::fromUtf8(u8"Engineering Economy – TT508"),
                                    QString::fromUtf8(u8"Methodology of Scientific and Technological Work – TT509")}},
                    SemestreCurricular{
                        QString::fromUtf8(u8"9th Semester"),
                        QStringList{QString::fromUtf8(u8"Steel Structures – TC523"),
                                    QString::fromUtf8(u8"Wood Structures – TC524"),
                                    QString::fromUtf8(u8"Foundation Engineering – TC525"),
                                    QString::fromUtf8(u8"Applied Electricity – TE144"),
                                    QString::fromUtf8(u8"Engineering and Society – TH511"),
                                    QString::fromUtf8(u8"Business Administration – TT510"),
                                    QString::fromUtf8(u8"Final Course Project I – TC581"),
                                    QString::fromUtf8(u8"Final Course Project I – TH581"),
                                    QString::fromUtf8(u8"Final Course Project I – TT581"),
                                    QString::fromUtf8(u8"Infrastructure and Special Works Project – TC595"),
                                    QString::fromUtf8(u8"Infrastructure and Special Works Project – TH595"),
                                    QString::fromUtf8(u8"Infrastructure and Special Works Project – TT595")}},
                    SemestreCurricular{QString::fromUtf8(u8"10th Semester"),
                                       QStringList{QString::fromUtf8(u8"Final Course Project II – TC582"),
                                                   QString::fromUtf8(u8"Final Course Project II – TH582"),
                                                   QString::fromUtf8(u8"Final Course Project II – TT582"),
                                                   QString::fromUtf8(u8"Final Course Project II – TC583"),
                                                   QString::fromUtf8(u8"Final Course Project II – TH583"),
                                                   QString::fromUtf8(u8"Final Course Project II – TT583"),
                                                   QString::fromUtf8(u8"Supervised Internship – TC585"),
                                                   QString::fromUtf8(u8"Supervised Internship – TH585"),
                                                   QString::fromUtf8(u8"Supervised Internship – TT585"),
                                                   QString::fromUtf8(u8"Building Projects – TC596"),
                                                   QString::fromUtf8(u8"Building Projects – TH596")}},
                    SemestreCurricular{
                        QString::fromUtf8(u8"Electives (minimum 6)"),
                        QStringList{
                            QString::fromUtf8(u8"Environmental Impact Assessment – TT059"),
                            QString::fromUtf8(u8"Engineering Valuations – TC064"),
                            QString::fromUtf8(u8"Traffic Engineering – TT056"),
                            QString::fromUtf8(u8"Economic Engineering of Water Resources – TH035"),
                            QString::fromUtf8(u8"Social Engineering – TH045"),
                            QString::fromUtf8(u8"Concrete Structures III – TC054"),
                            QString::fromUtf8(u8"Building Structures II – TC056"),
                            QString::fromUtf8(u8"Wood Structures – TC057"),
                            QString::fromUtf8(u8"Steel Structures II – TC055"),
                            QString::fromUtf8(u8"Graphic Expression III – CD035"),
                            QString::fromUtf8(u8"Railways – TT066"),
                            QString::fromUtf8(u8"Engineering Geology – TC049"),
                            QString::fromUtf8(u8"Environmental Geotechnics – TC053"),
                            QString::fromUtf8(u8"Applied Geotechnics to Transport Routes – TT065"),
                            QString::fromUtf8(u8"Landslide and Retaining Structures Geotechnics – TC052"),
                            QString::fromUtf8(u8"Project Management – TC062"),
                            QString::fromUtf8(u8"Water Resources Management – TH036"),
                            QString::fromUtf8(u8"Highways and Urban Roads Management – TT063"),
                            QString::fromUtf8(u8"Environmental Hydraulics – TH033"),
                            QString::fromUtf8(u8"River Hydraulics – TH032"),
                            QString::fromUtf8(u8"Specialized Building Installations – TC065"),
                            QString::fromUtf8(u8"Introduction to Occupational Safety Engineering – TT068"),
                            QString::fromUtf8(u8"Legislation and Professional Practice – TC061"),
                            QString::fromUtf8(u8"Logistics and Transport – TT058"),
                            QString::fromUtf8(u8"Rock Mechanics – TC051"),
                            QString::fromUtf8(u8"Finite Element Method Applied to Structural Engineering – TC059"),
                            QString::fromUtf8(u8"Urban Transport Planning and Modeling – TT060"),
                            QString::fromUtf8(u8"Planning and Management of Urban Systems – TH042"),
                            QString::fromUtf8(u8"Bridges and Special Structures – TC058"),
                            QString::fromUtf8(u8"Ports and Waterways – TT067"),
                            QString::fromUtf8(u8"Road Works Project – TT064"),
                            QString::fromUtf8(u8"Architecture Projects – TC060"),
                            QString::fromUtf8(u8"Urban Drainage Projects – TH037"),
                            QString::fromUtf8(u8"Hydraulic Works Projects – TH031"),
                            QString::fromUtf8(u8"Road Works Projects – TT064"),
                            QString::fromUtf8(u8"Urban Solid Waste Management Projects – TH038"),
                            QString::fromUtf8(u8"Environmental Sanitation Projects – TH039"),
                            QString::fromUtf8(u8"Sanitary Hydraulic Systems Projects – TH040"),
                            QString::fromUtf8(u8"Environmental Quality and Conservation – TH041"),
                            QString::fromUtf8(u8"Road Safety – TT061"),
                            QString::fromUtf8(u8"Water Resources Systems – TH034"),
                            QString::fromUtf8(u8"Geotechnical Investigation and Instrumentation Techniques – TC050"),
                            QString::fromUtf8(u8"Advanced Pavement Topics – TT062"),
                            QString::fromUtf8(u8"Advanced Geotechnics Topics – TC048"),
                            QString::fromUtf8(u8"Public Transport – TT057")}}}}}}};
    return cursos;
}
