#include "dicionario_disciplinas.hpp"

const QHash<QString, QStringList> &dicionario_disciplinas() {
    static const QHash<QString, QStringList> valores = {
        {QString::fromUtf8(u8"1ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Cálculo Diferencial e Integral I – CM201"),
                     QString::fromUtf8(u8"Mecânica Geral II – TC023"),
                     QString::fromUtf8(u8"Materiais de Construção Civil I – TC030"),
                     QString::fromUtf8(u8"Atividades Formativas – AAC005"),
                     QString::fromUtf8(u8"Laboratório de Materiais de Construção – TC039"),
                     QString::fromUtf8(u8"Pavimentação – TT051"),
                     QString::fromUtf8(u8"Trabalho Final de Curso II – TH062"),
                     QString::fromUtf8(u8"Ferrovias – TT066"),
                     QString::fromUtf8(u8"Fundamentos Físicos e Matemáticos para Edificações – EDF1001"),
                     QString::fromUtf8(u8"Projeto Integrado – EDF1025")}},
        {QString::fromUtf8(u8"2ª Coloracao Disciplina"),
         QStringList{
             QString::fromUtf8(u8""), QString::fromUtf8(u8"Eletricidade Aplicada – TE144"),
             QString::fromUtf8(u8"Métodos Numéricos – CI202"), QString::fromUtf8(u8"Mecânica dos Fluidos II – TH021"),
             QString::fromUtf8(u8"Equipamentos de Construção e Conservação – TT047"),
             QString::fromUtf8(u8"Obras Geotécnicas – TC066"), QString::fromUtf8(u8"Saneamento Ambiental II – TH029"),
             QString::fromUtf8(u8"Trabalho Final de Curso II – TT072"),
             QString::fromUtf8(u8"Geologia de Engenharia – TC049"),
             QString::fromUtf8(u8"Legislação e Prática Profissional – TC061"),
             QString::fromUtf8(u8"Informática Instrumental – EDF1002")}},
        {QString::fromUtf8(u8"3ª Coloracao Disciplina"),
         QStringList{
             QString::fromUtf8(u8""), QString::fromUtf8(u8"Expressão Gráfica I – CD027"),
             QString::fromUtf8(u8"Cálculo III – CM043"), QString::fromUtf8(u8"Resistência dos Materiais II – TC028"),
             QString::fromUtf8(u8"Hidráulica e Hidrologia Experimental – TH027"),
             QString::fromUtf8(u8"Planejamento de Transportes – TT049"),
             QString::fromUtf8(u8"Administração de Empresas de Engenharia I – TT008"),
             QString::fromUtf8(u8"Avaliação de Impactos Ambientais – TT059"),
             QString::fromUtf8(u8"Geotecnia Ambiental – TC053"), QString::fromUtf8(u8"Logística e Transporte – TT058"),
             QString::fromUtf8(u8"Desenho Técnico – EDF1003")}},
        {QString::fromUtf8(u8"4ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Geometria Analítica – CM045"),
                     QString::fromUtf8(u8"Construção Civil II – TC025"),
                     QString::fromUtf8(u8"Sistemas de Transporte – TT046"), QString::fromUtf8(u8"Hidrologia – TH024"),
                     QString::fromUtf8(u8"Saneamento Ambiental I – TH028"),
                     QString::fromUtf8(u8"Estrutura de Edifícios I – TC044"),
                     QString::fromUtf8(u8"Engenharia de Avaliações – TC064"),
                     QString::fromUtf8(u8"Geotecnia Aplicada as Vias de Transporte – TT065"),
                     QString::fromUtf8(u8"Mecânica das Rochas – TC051"),
                     QString::fromUtf8(u8"Desenho Digital Básico – EDF1004")}},
        {QString::fromUtf8(u8"5ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Introdução à Engenharia – TC022"),
                     QString::fromUtf8(u8"Estatística II – CE003"), QString::fromUtf8(u8"Topografia II – GA070"),
                     QString::fromUtf8(u8"Materiais de Construção Civil III – TC034"),
                     QString::fromUtf8(u8"Construção Civil IV – TC042"),
                     QString::fromUtf8(u8"Estruturas Metálicas I – TC043"),
                     QString::fromUtf8(u8"Engenharia de Tráfego – TT056"),
                     QString::fromUtf8(u8"Geotecnia de Taludes e Contenções – TC052"),
                     QString::fromUtf8(u8"Método dos Elementos Finitos Aplicados a Engenharia de Estruturas – TC059"),
                     QString::fromUtf8(u8"Técnicas Básicas de Construção Civil – EDF1005")}},
        {QString::fromUtf8(u8"6ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Mecânica Geral I – TC021"),
                     QString::fromUtf8(u8"Mecânica dos Fluidos I – TH019"),
                     QString::fromUtf8(u8"Estruturação Sanitária das Cidades – TH025"),
                     QString::fromUtf8(u8"Mecânica das Estruturas II – TC036"),
                     QString::fromUtf8(u8"Economia de Engenharia I – TT007"),
                     QString::fromUtf8(u8"Gerenciamento de Projetos – TC045"),
                     QString::fromUtf8(u8"Engenharia Econômica de Recursos Hídricos – TH035"),
                     QString::fromUtf8(u8"Gerenciamento de Empreendimentos – TC062"),
                     QString::fromUtf8(u8"Modelagem e Planejamento de Transportes Urbanos – TT060"),
                     QString::fromUtf8(u8"Materiais de Construção Civil – EDF1006")}},
        {QString::fromUtf8(u8"7ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Programação de Computadores – CI208"),
                     QString::fromUtf8(u8"Mecânica Geral III – TC027"), QString::fromUtf8(u8"Hidráulica – TH020"),
                     QString::fromUtf8(u8"Mecânica dos Solos – TC035"),
                     QString::fromUtf8(u8"Estágio Supervisionado – TC046"),
                     QString::fromUtf8(u8"Sistemas Prediais, Hidráulicos e Sanitários – TH030"),
                     QString::fromUtf8(u8"Estruturas de Concreto III – TC054"),
                     QString::fromUtf8(u8"Gerenciamento de Recursos Hídricos – TH036"),
                     QString::fromUtf8(u8"Higiene e Segurança do Trabalho – EDF1007")}},
        {QString::fromUtf8(u8"8ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Álgebra Linear – CM005"),
                     QString::fromUtf8(u8"Resistência dos Materiais I – TC026"),
                     QString::fromUtf8(u8"Infra-Estrutura Viária – TT048"),
                     QString::fromUtf8(u8"Construção Civil III – TC038"),
                     QString::fromUtf8(u8"Estágio Supervisionado – TH043"),
                     QString::fromUtf8(u8"Trabalho Final de Curso I – TC081"),
                     QString::fromUtf8(u8"Estruturas de Edifícios II – TC056"),
                     QString::fromUtf8(u8"Gerenciamento de Rodovias e Vias Urbanas – TT063"),
                     QString::fromUtf8(u8"Desenho Arquitetônico – EDF1008")}},
        {QString::fromUtf8(u8"9ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Cálculo Diferencial e Integral II – CM202"),
                     QString::fromUtf8(u8"Topografia I – GA069"),
                     QString::fromUtf8(u8"Laboratório de Mecânica dos Solos – TC033"),
                     QString::fromUtf8(u8"Engenharia de Recursos Hídricos – TH026"),
                     QString::fromUtf8(u8"Estágio Supervisionado – TT054"),
                     QString::fromUtf8(u8"Trabalho Final de Curso I – TH061"),
                     QString::fromUtf8(u8"Estruturas de Madeira – TC057"),
                     QString::fromUtf8(u8"Hidráulica Ambiental – TH033"),
                     QString::fromUtf8(u8"Desenho Digital Avançado – EDF1009")}},
        {QString::fromUtf8(u8"10ª Coloracao Disciplina"),
         QStringList{
             QString::fromUtf8(u8""), QString::fromUtf8(u8"Construção Civil I – TC024"),
             QString::fromUtf8(u8"Introdução à Engenharia Geotécnica – TC029"),
             QString::fromUtf8(u8"Materiais de Construção Civil II – TC031"),
             QString::fromUtf8(u8"Engenharia Social – TH045"), QString::fromUtf8(u8"Estruturas de Concreto II – TC040"),
             QString::fromUtf8(u8"Trabalho Final de Curso I – TT071"),
             QString::fromUtf8(u8"Estruturas Metálicas II – TC055"), QString::fromUtf8(u8"Hidráulica Fluvial – TH032"),
             QString::fromUtf8(u8"Resistência dos Materiais – EDF1010")}},
        {QString::fromUtf8(u8"11ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Expressão Gráfica II – CD028"),
                     QString::fromUtf8(u8"Ciências do Ambiente – TH022"),
                     QString::fromUtf8(u8"Mecânica das Estruturas I – TC032"),
                     QString::fromUtf8(u8"Estruturas de Concreto I – TC037"),
                     QString::fromUtf8(u8"Geotecnia de Fundações – TC041"),
                     QString::fromUtf8(u8"Trabalho Final de Curso II – TC082"),
                     QString::fromUtf8(u8"Expressão Gráfica III – CD035"),
                     QString::fromUtf8(u8"Instalações Prediais Especiais – TC065"),
                     QString::fromUtf8(u8"Tecnologia do Concreto – EDF1011")}},
        {QString::fromUtf8(u8"12ª Coloracao Disciplina"),
         QStringList{
             QString::fromUtf8(u8""), QString::fromUtf8(u8"Introdução a Engenharia de Segurança do Trabalho – TT068"),
             QString::fromUtf8(u8"Projetos de Drenagem Urbana – TH037"),
             QString::fromUtf8(u8"Tópicos Avançados em Geotecnia – TC048"),
             QString::fromUtf8(u8"Introdução à Geometria Analítica e Álgebra Linear – CM303"),
             QString::fromUtf8(u8"Mecânica dos Fluídos I – TH501"),
             QString::fromUtf8(u8"Mecânica dos Sólidos II – TC513"), QString::fromUtf8(u8"Hidrologia – TH505"),
             QString::fromUtf8(u8"Engenharia Urbana – TH594"), QString::fromUtf8(u8"Estruturas de Madeira – TC524"),
             QString::fromUtf8(u8"Práticas Básicas de Construção Civil – EDF1012")}},
        {QString::fromUtf8(u8"13ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Projetos de Obras Hidráulicas – TH031"),
                     QString::fromUtf8(u8"Transporte Público – TT057"), QString::fromUtf8(u8"Cálculo 1 – CM311"),
                     QString::fromUtf8(u8"Sistemas de Transporte – TT501"),
                     QString::fromUtf8(u8"Materiais de Construção Civil II – TC514"),
                     QString::fromUtf8(u8"Hidráulica e Hidrologia Experimental – TH506"),
                     QString::fromUtf8(u8"Engenharia Urbana – TT594"),
                     QString::fromUtf8(u8"Engenharia de Fundações – TC525"),
                     QString::fromUtf8(u8"Técnicas Complementares de Construção Civil – EDF1013")}},
        {QString::fromUtf8(u8"14ª Coloracao Disciplina"),
         QStringList{
             QString::fromUtf8(u8""), QString::fromUtf8(u8"Projetos de Obras Viárias – TT064"),
             QString::fromUtf8(u8"Expressão Gráfica A – CEG019"), QString::fromUtf8(u8"Desenho Arquitetônico – TC503"),
             QString::fromUtf8(u8"Cálculo 4 – CM314"), QString::fromUtf8(u8"Hidráulica – TH504"),
             QString::fromUtf8(u8"Equipamentos de Terraplanagem e de Pavimentação – TT503"),
             QString::fromUtf8(u8"Obras Geotécnicas – TC521"), QString::fromUtf8(u8"Eletricidade Aplicada – TE144"),
             QString::fromUtf8(u8"Mecânica dos Solos e Fundações – EDF1014")}},
        {QString::fromUtf8(u8"15ª Coloracao Disciplina"),
         QStringList{
             QString::fromUtf8(u8""), QString::fromUtf8(u8"Projetos de Sistemas de Resíduos Sólidos Urbanos – TH038"),
             QString::fromUtf8(u8"Fundamentação de Programação de Computadores – CI182"),
             QString::fromUtf8(u8"Análise Estrutural I – TC504"), QString::fromUtf8(u8"Topografia II – GA176"),
             QString::fromUtf8(u8"Ciências do Ambiente – TH508"),
             QString::fromUtf8(u8"Estruturação das Cidades – TH593"),
             QString::fromUtf8(u8"Estruturas de Concreto II – TC522"),
             QString::fromUtf8(u8"Engenharia e Sociedade – TH511"), QString::fromUtf8(u8"Topografia – EDF1015")}},
        {QString::fromUtf8(u8"16ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""),
                     QString::fromUtf8(u8"Projetos de Sistemas de Saneamento Ambiental – TH039"),
                     QString::fromUtf8(u8"Pré-Cálculo – CM310"), QString::fromUtf8(u8"Física II – TH512"),
                     QString::fromUtf8(u8"Construção Civil II – TC508"),
                     QString::fromUtf8(u8"Planejamento e Operação de Transportes – TT502"),
                     QString::fromUtf8(u8"Estruturação das Cidades – TT593"),
                     QString::fromUtf8(u8"Saneamento Ambiental II – TH510"),
                     QString::fromUtf8(u8"Administração de Empresas – TT510"),
                     QString::fromUtf8(u8"Sistemas Estruturais – EDF1016")}},
        {QString::fromUtf8(u8"17ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""),
                     QString::fromUtf8(u8"Projetos de Sistemas Prediais Hidráulicos Sanitários – TH040"),
                     QString::fromUtf8(u8"Física I – TC501"), QString::fromUtf8(u8"Introdução à Estatística – CE009"),
                     QString::fromUtf8(u8"Mecânica dos Sólidos I – TC509"),
                     QString::fromUtf8(u8"Engenharia Civil e Sustentabilidade – TC592"),
                     QString::fromUtf8(u8"Mecânica dos Solos – TC518"), QString::fromUtf8(u8"Estradas – TT505"),
                     QString::fromUtf8(u8"Trabalho Final de Curso I – TC581"),
                     QString::fromUtf8(u8"Teoria das Instalações Elétricas Prediais – EDF1017")}},
        {QString::fromUtf8(u8"18ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Qualidade e Conservação Ambiental – TH041"),
                     QString::fromUtf8(u8"Química Aplicada – TC502"), QString::fromUtf8(u8"Cálculo 2 – CM312"),
                     QString::fromUtf8(u8"Materiais de Construção Civil I – TC510"),
                     QString::fromUtf8(u8"Engenharia Civil e Sustentabilidade – TH592"),
                     QString::fromUtf8(u8"Estruturas de Concreto I – TC519"),
                     QString::fromUtf8(u8"Pavimentação – TT506"),
                     QString::fromUtf8(u8"Trabalho Final de Curso I – TH581"),
                     QString::fromUtf8(u8"Teoria das Instalações Hidráulicas Prediais – EDF1018")}},
        {QString::fromUtf8(u8"19ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Segurança Viária – TT061"),
                     QString::fromUtf8(u8"Introdução à Engenharia e Inovação – TC591"),
                     QString::fromUtf8(u8"Topografia I – GA175"),
                     QString::fromUtf8(u8"Laboratório de Materiais de Construção Civil – TC511"),
                     QString::fromUtf8(u8"Engenharia Civil e Sustentabilidade – TT592"),
                     QString::fromUtf8(u8"Gestão de Projetos – TC520"),
                     QString::fromUtf8(u8"Laboratório de Transportes – TT507"),
                     QString::fromUtf8(u8"Trabalho Final de Curso I – TT581"),
                     QString::fromUtf8(u8"Projeto Arquitetônico – EDF1019")}},
        {QString::fromUtf8(u8"20ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Sistemas de Recursos Hídricos – TH034"),
                     QString::fromUtf8(u8"Introdução à Engenharia e Inovação – TH591"),
                     QString::fromUtf8(u8"Construção Civil I – TC505"),
                     QString::fromUtf8(u8"Mecânica dos Fluídos II – TH502"),
                     QString::fromUtf8(u8"Hidráulica dos Solos – TC515"),
                     QString::fromUtf8(u8"Engenharia de Recursos Hídricos – TH507"),
                     QString::fromUtf8(u8"Economia de Engenharia – TT508"),
                     QString::fromUtf8(u8"Projeto de Infraestrutura e Obras Especiais – TC595"),
                     QString::fromUtf8(u8"Práticas Complementares e Instalações Prediais – EDF1020")}},
        {QString::fromUtf8(u8"21ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""),
                     QString::fromUtf8(u8"Técnica de Investigação Geotécnica e Instrumentação – TC050"),
                     QString::fromUtf8(u8"Introdução a Engenharia e Inovação – TT591"),
                     QString::fromUtf8(u8"Análise Estrutural II – TC506"),
                     QString::fromUtf8(u8"Mecânica dos Fluídos Experimental – TH503"),
                     QString::fromUtf8(u8"Análise Estrutural III – TC516"),
                     QString::fromUtf8(u8"Saneamento Ambiental I – TH509"),
                     QString::fromUtf8(u8"Metodologia do Trabalho Científico e Tecnológico – TT509"),
                     QString::fromUtf8(u8"Projeto de Infraestrutura e Obras Especiais – TH595"),
                     QString::fromUtf8(u8"Impactos Ambientais – EDF1021")}},
        {QString::fromUtf8(u8"22ª Coloracao Disciplina"),
         QStringList{
             QString::fromUtf8(u8""), QString::fromUtf8(u8"Tópicos Avançados de Pavimentação – TT062"),
             QString::fromUtf8(u8"Métodos Numéricos – CI202"), QString::fromUtf8(u8"Sistemas Estruturais – TC507"),
             QString::fromUtf8(u8"Caracterização Geológica - Geotécnica – TC512"),
             QString::fromUtf8(u8"Construção Civil III – TC517"), QString::fromUtf8(u8"Engenharia Econômica – TT504"),
             QString::fromUtf8(u8"Estruturas de Aço – TC523"),
             QString::fromUtf8(u8"Projeto de Infraestrutura e Obras Especiais – TT595"),
             QString::fromUtf8(u8"Gestão de Obras – EDF1022")}},
        {QString::fromUtf8(u8"23ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Trabalho Final de Curso II – TC583"),
                     QString::fromUtf8(u8"Trabalho Final de Curso II – TH583"),
                     QString::fromUtf8(u8"Trabalho Final de Curso II – TT583"),
                     QString::fromUtf8(u8"Estágio Supervisionado Obrigatório – TC585"),
                     QString::fromUtf8(u8"Estágio Supervisionado Obrigatório – TH585"),
                     QString::fromUtf8(u8"Estágio Supervisionado Obrigatório – TT585"),
                     QString::fromUtf8(u8"Projetos de Edifícios – TC596"),
                     QString::fromUtf8(u8"Projetos de Edifícios – TH596"),
                     QString::fromUtf8(u8"Orçamento de Obras – EDF1023")}},
        {QString::fromUtf8(u8"24ª Coloracao Disciplina"),
         QStringList{QString::fromUtf8(u8""), QString::fromUtf8(u8"Planejamento e Gestão dos Sistemas Urbanos – TH042"),
                     QString::fromUtf8(u8"Pontes e Estruturas Especiais – TC058"),
                     QString::fromUtf8(u8"Portos e Hidrovias – TT067"),
                     QString::fromUtf8(u8"Projeto de Obras Viárias – TT064"),
                     QString::fromUtf8(u8"Projetos de Arquitetura – TC060"),
                     QString::fromUtf8(u8"Trabalho Final de Curso II – TC582"),
                     QString::fromUtf8(u8"Trabalho Final de Curso II – TH582"),
                     QString::fromUtf8(u8"Trabalho Final de Curso II – TT582"),
                     QString::fromUtf8(u8"Planejamento de Obras – EDF1024")}}};
    return valores;
}
